# $Id$
DEPINC += -Iexternal/libz/include
L_OBJS += external/libz/src/adler32.o external/libz/src/compress.o external/libz/src/crc32.o external/libz/src/deflate.o external/libz/src/gzclose.o external/libz/src/gzlib.o external/libz/src/gzread.o external/libz/src/gzwrite.o external/libz/src/infback.o external/libz/src/inffast.o external/libz/src/inflate.o external/libz/src/inftrees.o external/libz/src/trees.o external/libz/src/uncompr.o external/libz/src/zutil.o 

DEPINC += -Iexternal/libjpeg/include
L_OBJS += external/libjpeg/src/cdjpeg.o external/libjpeg/src/jaricom.o external/libjpeg/src/jcapimin.o external/libjpeg/src/jcapistd.o external/libjpeg/src/jcarith.o external/libjpeg/src/jccoefct.o external/libjpeg/src/jccolor.o external/libjpeg/src/jcdctmgr.o external/libjpeg/src/jchuff.o external/libjpeg/src/jcinit.o external/libjpeg/src/jcmainct.o external/libjpeg/src/jcmarker.o external/libjpeg/src/jcmaster.o external/libjpeg/src/jcomapi.o external/libjpeg/src/jcparam.o external/libjpeg/src/jcprepct.o external/libjpeg/src/jcsample.o external/libjpeg/src/jctrans.o external/libjpeg/src/jdapimin.o external/libjpeg/src/jdapistd.o external/libjpeg/src/jdarith.o external/libjpeg/src/jdatadst.o external/libjpeg/src/jdatasrc.o external/libjpeg/src/jdcoefct.o external/libjpeg/src/jdcolor.o external/libjpeg/src/jddctmgr.o external/libjpeg/src/jdhuff.o external/libjpeg/src/jdinput.o external/libjpeg/src/jdmainct.o external/libjpeg/src/jdmarker.o external/libjpeg/src/jdmaster.o external/libjpeg/src/jdmerge.o external/libjpeg/src/jdpostct.o external/libjpeg/src/jdsample.o external/libjpeg/src/jdtrans.o external/libjpeg/src/jerror.o external/libjpeg/src/jfdctflt.o external/libjpeg/src/jfdctfst.o external/libjpeg/src/jfdctint.o external/libjpeg/src/jidctflt.o external/libjpeg/src/jidctfst.o external/libjpeg/src/jidctint.o external/libjpeg/src/jmemmgr.o external/libjpeg/src/jmemnobs.o external/libjpeg/src/jquant1.o external/libjpeg/src/jquant2.o external/libjpeg/src/jutils.o external/libjpeg/src/rdbmp.o external/libjpeg/src/rdcolmap.o external/libjpeg/src/rdgif.o external/libjpeg/src/rdppm.o external/libjpeg/src/rdrle.o external/libjpeg/src/rdswitch.o external/libjpeg/src/rdtarga.o external/libjpeg/src/transupp.o external/libjpeg/src/wrbmp.o external/libjpeg/src/wrgif.o external/libjpeg/src/wrppm.o external/libjpeg/src/wrrle.o external/libjpeg/src/wrtarga.o

DEPINC += -Iexternal/libpng/include
L_OBJS += external/libpng/src/png.o external/libpng/src/pngerror.o external/libpng/src/pngget.o external/libpng/src/pngmem.o external/libpng/src/pngpread.o external/libpng/src/pngread.o external/libpng/src/pngrio.o external/libpng/src/pngrtran.o external/libpng/src/pngrutil.o external/libpng/src/pngset.o external/libpng/src/pngtrans.o external/libpng/src/pngwio.o external/libpng/src/pngwrite.o external/libpng/src/pngwtran.o external/libpng/src/pngwutil.o
