/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char *MwIconInfo[] = {
/* columns rows colors chars-per-pixel */
"32 32 3 1 ",
"  c DarkSlateGray",
". c blue",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXX.....XXXXXXXXXX",
"XXXXXXXXXXXXXXXX.......XXXXXXXXX",
"XXXXXXXXXXXXXXXXX.....  XXXXXXXX",
"XXXXXXXXXXXXXXXXX     XXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXX......XXXXXXXXXXXX",
"XXXXXXXXXXXX.......  XXXXXXXXXXX",
"XXXXXXXX..........  XXXXXXXXXXXX",
"XXXXXXXXX   .....  XXXXXXXXXXXXX",
"XXXXXXXXXXX.....  XXXXXXXXXXXXXX",
"XXXXXXXXXX.....  XXXXXXXXXXXXXXX",
"XXXXXXXXXX.....  XXXXXXXXXXXXXXX",
"XXXXXXXXX.....  XXXXXXXXXXXXXXXX",
"XXXXXXXX.....  XXXXXXXXXXXXXXXXX",
"XXXXXXXX.....  XXXXXXXXXXXXXXXXX",
"XXXXXXXX....  XXXXXXXXXXXXXXXXXX",
"XXXXXXXX....  XXXXXXXXXXXXXXXXXX",
"XXXXXXXX....  XXXX.XXXXXXXXXXXXX",
"XXXXXXXXX.... XX...  XXXXXXXXXXX",
"XXXXXXXXXX.......   XXXXXXXXXXXX",
"XXXXXXXXXXX       XXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
