/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char* MwIconNews[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 6 1 ",
    "  c None",
    ". c black",
    "X c white",
    "o c SlateGray",
    "O c gray",
    "+ c #6632F7",
    /* pixels */
    "                                ",
    "                                ",
    "                                ",
    "            ...                 ",
    "           .XXX..               ",
    "          .XX.XXX..             ",
    "         .XX..X.XXX..           ",
    "        .XX.X..XX.oXX..         ",
    "       .XX.XX.XX.Xo.XXX..       ",
    "      .XOXXX.XX.O.XX.XXXX..     ",
    "     .XXo.oXXX.oXXX.XoXoXXX..   ",
    "    .XOXXXo.OXXO.X.Xo.X.X.oXX.. ",
    "   .XXo.oXXXO.oXXX...X.X.Xo.XXX.",
    "  .XOXXXo.OXXXo.oXXX..XXX.XXXX.O",
    " .XXo.oXXXO.oXXXOX.XXX.oX.XXX.O.",
    ".oOXXXo.OXXXo.oXX.X..XXo.XXX.O.O",
    ".Xo.oXXXO.oXXXOX.OXXX..XXXX.O.O.",
    ".XXXo.OXXXo.oXX.OOOOXXX.XX.O.O.O",
    ".O.oXXO.oXXXOX.oooOOOO.XX.O.O.O.",
    ".oOO.oXXo.oXXX..ooooO.XX.O.O.O. ",
    " ..oOOOoXXoOOXXX..oo.XX.O.O.O.  ",
    "   ..oOO.oXXO.oXXX..XX.O.O.O.   ",
    "     ..oOO.oXXo.oXXXX.O.O.O.    ",
    "       ..oOXOoXXo.XX.O.O.O.     ",
    "         ..oOo.oXXX.O.O.O.      ",
    "           ..oOO.X.O.O.O.       ",
    "             ..oOO.O..O.        ",
    "               ..o.oOO.         ",
    "                 .....          ",
    "                                ",
    "                                ",
    "                                "};
