/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char* MwIconNote[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 6 1 ",
    "  c None",
    ". c red",
    "X c white",
    "o c SlateGray",
    "O c firebrick",
    "+ c lavender",
    /* pixels */
    "               ....             ",
    "             ........           ",
    "            ..XX......o         ",
    "            .XX.......oo        ",
    "           ..X........Oo        ",
    "           .XX........Ooo       ",
    "           .X.........Ooo       ",
    "           .X.........Ooo       ",
    "           ...........Ooo       ",
    "           ...........Ooo       ",
    "           ..........Ooo        ",
    "           ..........Ooo        ",
    "           .........Oooo        ",
    "           .........Ooo         ",
    "           .........Ooo         ",
    "           ........Oooo         ",
    "            .......Ooo          ",
    "            ......Oooo          ",
    "            ......Ooo           ",
    "             ....Oooo           ",
    "             ....Ooo            ",
    "              OOOooo            ",
    "                ooo             ",
    "            .....               ",
    "           .XX...Oo             ",
    "          .XX.....Oo            ",
    "          .X......Ooo           ",
    "          ........Ooo           ",
    "          ........Ooo           ",
    "           O.....Oooo           ",
    "            OOOOOooo            ",
    "              ooooo             "};
