/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char* MwIconNote[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 7 1 ",
    "  c black",
    ". c red",
    "X c yellow",
    "o c magenta",
    "O c gray",
    "+ c white",
    "@ c None",
    /* pixels */
    "@@@@@@     @@@@@@@@@@@@@@@@@@@@@",
    "@@@@@ ..... @@@@@@@@@@@@@@@@@@@@",
    "@@@@ ....... @@@@@@@@@@@@@@@@@@@",
    "@@@@ ......o @@@@@@@@@@@@@@@@@@@",
    "@@@@ .oo++o. @@@@@  @@@@@@@@@@@@",
    "@@@@@ ..++. @@@@  X+ @@@@@@@@@@@",
    "@@@@@@     @@@  +X+X @@@@@@@@@@@",
    "@@@@@  ...    X+X+X+X @@@@@@@@@@",
    "@@@@ . ..+ . X+X+X+X+ @@@@@@@@@@",
    "@@@ .. ..o .o X+X+X+X+ @@@@@@@@@",
    "@@@ ...   ..o +X+X+X+X @@@@@@@@@",
    "@@@ .o.....o. X+X+X+X+X @@@@@@@@",
    "@@  ..oo++o.. +X+X+X+X+ @@@@@@@@",
    "  O  ....... +X+X+X+X+X+ @@@@@@@",
    " OOO        +X+X+X+X+X+X @@@@@@@",
    "@ O O O  +X+X+X+X+XOO+X+X @@@@@@",
    "@ OO O O X+X+X+X+OOX+X+X+ @@@@@@",
    "@@ OO O O+X+XOXOO+X+X+X+X+ @@@@@",
    "@@ OOO O+X+X+OOX+O+X+OOX+X @@@@@",
    "@@@ O+X+X+XOO+X+X+XOO+X+X+X @@@@",
    "@@@ OO+X+OOXOO+X+OOX+O+X+X+X @@@",
    "@@@@ OX+X+X+X+XOO+X+X+X+OOX+X   ",
    "@@@@ OOX+X+XOOOX+X+X+XOO+X+X+X+ ",
    "@@@@@ O+X+OOX+XOXOX+OOX+X+X+X+ @",
    "@@@@@ OO+X+X+X+X+XOO+XOX+X+X+ @@",
    "@@@@@@ OX+X+X+X+OOX+X+X+X+X  @@@",
    "@@@@@@  OX+X+X+X+X+X+X+X+  @@@@@",
    "@@@@@@@    +X+X+X+X+X+X  @@@@@@@",
    "@@@@@@@@       X+X+X+  @@@@@@@@@",
    "@@@@@@@@@  X++  X+X  @@@@@@@@@@@",
    "@@@@@@@@@@   X     @@@@@@@@@@@@@",
    "@@@@@@@@@@@@     @@@@@@@@@@@@@@@"};
