/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char* MwIconQuestion[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 5 1 ",
    "  c firebrick",
    ". c red",
    "X c orange",
    "o c SlateGray",
    "O c None",
    /* pixels */
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "OOOOOOOOOOXXXXXXXXXXXOOOOOOOOOOO",
    "OOOOOOOOXX.............OOOOOOOOO",
    "OOOOOOOX.....         ..oOOOOOOO",
    "OOOOOOX....             .oOOOOOO",
    "OOOOOX....    ....       .oOOOOO",
    "OOOOX....    oooO..        oOOOO",
    "OOOX....    oooOOO..       ooOOO",
    "OOOX...     ooOOOOX..      ooOOO",
    "OOOX...      oOOOOX..      ooOOO",
    "OOOO...      ooOOOX..      ooOOO",
    "OOOOO..      ooOOX...      ooOOO",
    "OOOOOO..    oooOOX..      oooOOO",
    "OOOOOOO..  oooOOX..      oooOOOO",
    "OOOOOOOOoooooOOX..      ooooOOOO",
    "OOOOOOOOOoooOOX..      ooooOOOOO",
    "OOOOOOOOOOOOOX..     oooooOOOOOO",
    "OOOOOOOOOOOOX..     ooooOOOOOOOO",
    "OOOOOOOOOOOX..     ooooOOOOOOOOO",
    "OOOOOOOOOOOX..    ooooOOOOOOOOOO",
    "OOOOOOOOOOOO..   ooooOOOOOOOOOOO",
    "OOOOOOOOOOOOO.. ooooOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOoooooOOOOOOOOOOOOO",
    "OOOOOOOOOOOOX..  oOOOOOOOOOOOOOO",
    "OOOOOOOOOOOX.X..  OOOOOOOOOOOOOO",
    "OOOOOOOOOOX.X.X..  OOOOOOOOOOOOO",
    "OOOOOOOOOOX..X...  oOOOOOOOOOOOO",
    "OOOOOOOOOOO......  ooOOOOOOOOOOO",
    "OOOOOOOOOOOO....  oooOOOOOOOOOOO",
    "OOOOOOOOOOOOO.   ooooOOOOOOOOOOO",
    "OOOOOOOOOOOOOOooooooOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOooooOOOOOOOOOOOOO"};
