/* $Id$ */
#include <Mw/Milsko.h>

/* XPM */
char* MwIconWarning[] = {
    /* columns rows colors chars-per-pixel */
    "32 32 6 1 ",
    "  c None",
    ". c red",
    "X c yellow",
    "o c DarkSlateGray",
    "O c black",
    "+ c #6632F7",
    /* pixels */
    "                                ",
    "                                ",
    "              ...               ",
    "             .....              ",
    "             ..X..oo            ",
    "            ..XXX..oo           ",
    "            ..XXX..oo           ",
    "           ..XXXXX..oo          ",
    "           ..XXXXX..oo          ",
    "          ..XXOOOXX..oo         ",
    "          ..XOOOOOX..oo         ",
    "         ..XXOOOOOXX..oo        ",
    "         ..XXOOOOOXX..oo        ",
    "        ..XXXOOOOOXXX..oo       ",
    "        ..XXXOOOOOXXX..oo       ",
    "       ..XXXXOOOOOXXXX..oo      ",
    "       ..XXXXOOOOOXXXX..oo      ",
    "      ..XXXXXOOOOOXXXXX..oo     ",
    "      ..XXXXXXOOOXXXXXX..oo     ",
    "     ..XXXXXXXOOOXXXXXXX..oo    ",
    "     ..XXXXXXXOOOXXXXXXX..oo    ",
    "    ..XXXXXXXXOOOXXXXXXXX..oo   ",
    "    ..XXXXXXXXXXXXXXXXXXX..oo   ",
    "   ..XXXXXXXXXOOOXXXXXXXXX..oo  ",
    "   ..XXXXXXXXOOOOOXXXXXXXX..oo  ",
    "  ..XXXXXXXXXOOOOOXXXXXXXXX..oo ",
    "  ..XXXXXXXXXXOOOXXXXXXXXXX..oo ",
    " ..XXXXXXXXXXXXXXXXXXXXXXXXX..oo",
    " .............................oo",
    "  ...........................ooo",
    "    ooooooooooooooooooooooooooo ",
    "                                "};
